import React, { useEffect, useState } from "react";
import styles from "../../styles/Element.module.css";
import Reco from "./Recommand/Reco";
import Reco2 from "./Recommand/Reco2";

function Elements() {
  const [data, setdata] = useState(
    {
    items: [
      {
        id: "tt15791034",
        rank: "1",
        rankUpDown: "+1",
        title: "Barbarian",
        fullTitle: "Barbarian (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BN2M3Y2NhMGYtYjUxOS00M2UwLTlmMGUtYzY4MzFlNjZkYzY2XkEyXkFqcGdeQXVyODc0OTEyNDU@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Zach Cregger (dir.), Georgina Campbell, Bill Skarsgård",
        imDbRating: "7.1",
        imDbRatingCount: "73453",
      },
      {
        id: "tt1016150",
        rank: "2",
        rankUpDown: "+11",
        title: "All Quiet on the Western Front",
        fullTitle: "All Quiet on the Western Front (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BYTE1MmZiMWYtYTFmZi00YjA3LWI2ODgtMWFlNWYxZjdmNGE3XkEyXkFqcGdeQXVyNjk1Njg5NTA@._V1_UY176_CR6,0,128,176_AL_.jpg",
        crew: "Edward Berger (dir.), Felix Kammerer, Albrecht Schuch",
        imDbRating: "7.9",
        imDbRatingCount: "51439",
      },
      {
        id: "tt10403420",
        rank: "3",
        rankUpDown: "0",
        title: "Terrifier 2",
        fullTitle: "Terrifier 2 (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BNTc5YWQ2MzAtM2E3Yi00MDUyLWFiYzctMzQ5NWVkMmQ0OTcxXkEyXkFqcGdeQXVyMTU2MDk3MDQz._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Damien Leone (dir.), Lauren LaVera, David Howard Thornton",
        imDbRating: "6.3",
        imDbRatingCount: "16799",
      },
      {
        id: "tt6443346",
        rank: "4",
        rankUpDown: "-3",
        title: "Black Adam",
        fullTitle: "Black Adam (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BYzZkOGUwMzMtMTgyNS00YjFlLTg5NzYtZTE3Y2E5YTA5NWIyXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Jaume Collet-Serra (dir.), Dwayne Johnson, Aldis Hodge",
        imDbRating: "7.0",
        imDbRatingCount: "109515",
      },
      {
        id: "tt4273800",
        rank: "5",
        rankUpDown: "+1",
        title: "The Good Nurse",
        fullTitle: "The Good Nurse (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BOGZhODQ3NDUtMjE1OS00MzEzLWFhY2MtY2U2YjQzYWUyYWQwXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Tobias Lindholm (dir.), Eddie Redmayne, Jessica Chastain",
        imDbRating: "6.9",
        imDbRatingCount: "32951",
      },
      {
        id: "tt1630029",
        rank: "6",
        rankUpDown: "+33",
        title: "Avatar: The Way of Water",
        fullTitle: "Avatar: The Way of Water (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BM2VhYjIwMDQtZjY4OS00Yjk2LWI5YjktNjQxOTE0MjE4NjBkXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "James Cameron (dir.), Zoe Saldana, Sigourney Weaver",
        imDbRating: "",
        imDbRatingCount: "0",
      },
      {
        id: "tt9114286",
        rank: "7",
        rankUpDown: "+1",
        title: "Black Panther: Wakanda Forever",
        fullTitle: "Black Panther: Wakanda Forever (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BNTM4NjIxNmEtYWE5NS00NDczLTkyNWQtYThhNmQyZGQzMjM0XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Ryan Coogler (dir.), Letitia Wright, Lupita Nyong'o",
        imDbRating: "7.5",
        imDbRatingCount: "35668",
      },
      {
        id: "tt17076046",
        rank: "8",
        rankUpDown: "+217",
        title: "Weird: The Al Yankovic Story",
        fullTitle: "Weird: The Al Yankovic Story (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BOWRiNmI1OTItYjc0Zi00YTYwLWI4OTEtMmE0YTNlODJkOTQwXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Eric Appel (dir.), Diedrich Bader, Daniel Radcliffe",
        imDbRating: "7.2",
        imDbRatingCount: "11772",
      },
      {
        id: "tt15474916",
        rank: "9",
        rankUpDown: "+7",
        title: "Smile",
        fullTitle: "Smile (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BZjE2ZWIwMWEtNGFlMy00ZjYzLWEzOWEtYzQ0MDAwZDRhYzNjXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Parker Finn (dir.), Sosie Bacon, Jessie T. Usher",
        imDbRating: "6.8",
        imDbRatingCount: "47305",
      },
      {
        id: "tt14641788",
        rank: "10",
        rankUpDown: "+144",
        title: "Enola Holmes 2",
        fullTitle: "Enola Holmes 2 (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BMDI1NWM1ZDItNDFhMi00YWRhLTg1YzItNTNhY2M2N2QzY2FkXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Harry Bradbeer (dir.), Millie Bobby Brown, Henry Cavill",
        imDbRating: "6.8",
        imDbRatingCount: "32718",
      },
      {
        id: "tt2935622",
        rank: "11",
        rankUpDown: "-7",
        title: "The School for Good and Evil",
        fullTitle: "The School for Good and Evil (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BNzM1ODI4Y2UtMGYxMS00OTUxLWE4NzItNjgxMTM2NzRjZThkXkEyXkFqcGdeQXVyMTA1OTcyNDQ4._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Paul Feig (dir.), Kit Young, Sophia Anne Caruso",
        imDbRating: "5.8",
        imDbRatingCount: "20491",
      },
      {
        id: "tt4281724",
        rank: "12",
        rankUpDown: "0",
        title: "Terrifier",
        fullTitle: "Terrifier (2016)",
        year: "2016",
        image:
          "https://m.media-amazon.com/images/M/MV5BYmMxNzA0OTUtOTJiOS00NTc4LWJmNTItMGM3OWE0N2Y0NjhjXkEyXkFqcGdeQXVyMTg5NjU4NjE@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Damien Leone (dir.), Jenna Kanell, Samantha Scaffidi",
        imDbRating: "5.6",
        imDbRatingCount: "30487",
      },
      {
        id: "tt13640696",
        rank: "13",
        rankUpDown: "+156",
        title: "See How They Run",
        fullTitle: "See How They Run (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BNzU5OTNmZDYtZjA4OC00YmQyLTk4ZjctMzVlZTYyYTE3ODUwXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Tom George (dir.), Kieran Hodgson, Pearl Chanda",
        imDbRating: "6.5",
        imDbRatingCount: "22908",
      },
      {
        id: "tt0107120",
        rank: "14",
        rankUpDown: "+6",
        title: "Hocus Pocus",
        fullTitle: "Hocus Pocus (1993)",
        year: "1993",
        image:
          "https://m.media-amazon.com/images/M/MV5BNWM3NmRhMGMtOGE4ZC00MDk0LWI1NjMtMjVlNTEwOTcwZTc0XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Kenny Ortega (dir.), Bette Midler, Sarah Jessica Parker",
        imDbRating: "6.9",
        imDbRatingCount: "142521",
      },
      {
        id: "tt13560574",
        rank: "15",
        rankUpDown: "+2",
        title: "X",
        fullTitle: "X (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BMTJiMmE5YWItOWZjYS00YTg0LWE0MTYtMzg2ZTY4YjNkNDEzXkEyXkFqcGdeQXVyMTAzMDg4NzU0._V1_UY176_CR6,0,128,176_AL_.jpg",
        crew: "Ti West (dir.), Mia Goth, Jenna Ortega",
        imDbRating: "6.6",
        imDbRatingCount: "84706",
      },
      {
        id: "tt17220704",
        rank: "16",
        rankUpDown: "+42",
        title: "A Christmas Story Christmas",
        fullTitle: "A Christmas Story Christmas (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BMjliZjM5MWMtMzcyYi00Y2ZiLTliOGMtNGNjMjE1YWIwZTkyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Clay Kaytis (dir.), Peter Billingsley, Zack Ward",
        imDbRating: "",
        imDbRatingCount: "0",
      },
      {
        id: "tt10665342",
        rank: "17",
        rankUpDown: "-7",
        title: "Halloween Ends",
        fullTitle: "Halloween Ends (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BZTg1Y2Q3MzctMDlkOS00OGE1LWE4MjUtNmJjNDNkZmM2YmVkXkEyXkFqcGdeQXVyMjY5ODI4NDk@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "David Gordon Green (dir.), Jamie Lee Curtis, Andi Matichak",
        imDbRating: "5.0",
        imDbRatingCount: "48362",
      },
      {
        id: "tt10731256",
        rank: "18",
        rankUpDown: "-9",
        title: "Don't Worry Darling",
        fullTitle: "Don't Worry Darling (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BMzFkMWUzM2ItZWFjMi00NDY0LTk2MDMtZDhkMDE2MjRlYmZlXkEyXkFqcGdeQXVyNTAzNzgwNTg@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Olivia Wilde (dir.), Florence Pugh, Harry Styles",
        imDbRating: "6.2",
        imDbRatingCount: "56719",
      },
      {
        id: "tt11813216",
        rank: "19",
        rankUpDown: "0",
        title: "The Banshees of Inisherin",
        fullTitle: "The Banshees of Inisherin (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BM2NlZDI0ZDktNTg5OS00ZjQ1LWI4MDEtN2I0MDE5NWRiNzA4XkEyXkFqcGdeQXVyMTY5Nzc4MDY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Martin McDonagh (dir.), Colin Farrell, Brendan Gleeson",
        imDbRating: "8.2",
        imDbRatingCount: "11436",
      },
      {
        id: "tt12593682",
        rank: "20",
        rankUpDown: "-2",
        title: "Bullet Train",
        fullTitle: "Bullet Train (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BMDU2ZmM2OTYtNzIxYy00NjM5LTliNGQtN2JmOWQzYTBmZWUzXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "David Leitch (dir.), Brad Pitt, Joey King",
        imDbRating: "7.3",
        imDbRatingCount: "172277",
      },
      {
        id: "tt11909878",
        rank: "21",
        rankUpDown: "+1",
        title: "Hocus Pocus 2",
        fullTitle: "Hocus Pocus 2 (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BODcxYzI1MTktZWYzNC00MGZlLWI3ZjYtNzhmM2IyOTlkNjYyXkEyXkFqcGdeQXVyMTA1OTcyNDQ4._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Anne Fletcher (dir.), Bette Midler, Sarah Jessica Parker",
        imDbRating: "6.0",
        imDbRatingCount: "41659",
      },
      {
        id: "tt18925334",
        rank: "22",
        rankUpDown: "-8",
        title: "Pearl",
        fullTitle: "Pearl (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BZTFkNmE5MjUtZDE1Yi00ZmQyLTk2YWUtN2EwODA1ZmNlOTA5XkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Ti West (dir.), Mia Goth, David Corenswet",
        imDbRating: "7.1",
        imDbRatingCount: "22182",
      },
      {
        id: "tt8093700",
        rank: "23",
        rankUpDown: "+19",
        title: "The Woman King",
        fullTitle: "The Woman King (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BY2I4MDIwYWUtOWMxNC00ZTIzLWE3OGYtOWUyMmIwZGE2NjU4XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_UY176_CR6,0,128,176_AL_.jpg",
        crew: "Gina Prince-Bythewood (dir.), Viola Davis, Thuso Mbedu",
        imDbRating: "6.7",
        imDbRatingCount: "30628",
      },
      {
        id: "tt1596342",
        rank: "24",
        rankUpDown: "+96",
        title: "Disenchanted",
        fullTitle: "Disenchanted (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BNDVhYjU1ZjUtNzI3Ni00Mzg5LWJhNGYtMjE3Y2FlZWY2Y2Y2XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Adam Shankman (dir.), Amy Adams, Alan Tudyk",
        imDbRating: "",
        imDbRatingCount: "0",
      },
      {
        id: "tt14109724",
        rank: "25",
        rankUpDown: "-10",
        title: "Ticket to Paradise",
        fullTitle: "Ticket to Paradise (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BMWE0MmEwMWUtZjRjOC00YzE3LWI2MjctNjc3NWQ0YTVmNDQ4XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Ol Parker (dir.), George Clooney, Sean Lynch",
        imDbRating: "6.2",
        imDbRatingCount: "21586",
      },
      {
        id: "tt5181830",
        rank: "26",
        rankUpDown: "+67",
        title: "Wendell & Wild",
        fullTitle: "Wendell & Wild (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BMDZlMjcwZjMtYTQ3YS00N2IzLWI5ZWItZDY1YTMzZTE5YTFmXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Henry Selick (dir.), Lyric Ross, Keegan-Michael Key",
        imDbRating: "6.5",
        imDbRatingCount: "5410",
      },
      {
        id: "tt0077651",
        rank: "27",
        rankUpDown: "+2",
        title: "Halloween",
        fullTitle: "Halloween (1978)",
        year: "1978",
        image:
          "https://m.media-amazon.com/images/M/MV5BNzk1OGU2NmMtNTdhZC00NjdlLWE5YTMtZTQ0MGExZTQzOGQyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "John Carpenter (dir.), Donald Pleasence, Jamie Lee Curtis",
        imDbRating: "7.7",
        imDbRatingCount: "281336",
      },
      {
        id: "tt1745960",
        rank: "28",
        rankUpDown: "-4",
        title: "Top Gun: Maverick",
        fullTitle: "Top Gun: Maverick (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BZWYzOGEwNTgtNWU3NS00ZTQ0LWJkODUtMmVhMjIwMjA1ZmQwXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Joseph Kosinski (dir.), Tom Cruise, Jennifer Connelly",
        imDbRating: "8.4",
        imDbRatingCount: "424064",
      },
      {
        id: "tt7322224",
        rank: "29",
        rankUpDown: "-6",
        title: "Triangle of Sadness",
        fullTitle: "Triangle of Sadness (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BNDRiZjc0ZDMtMjhlYi00ZjAzLTg0MDQtZDI2NGEyYTBlN2M2XkEyXkFqcGdeQXVyMTA2MDU0NjM5._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Ruben Östlund (dir.), Harris Dickinson, Charlbi Dean",
        imDbRating: "7.9",
        imDbRatingCount: "16027",
      },
      {
        id: "tt13139228",
        rank: "30",
        rankUpDown: "+52",
        title: "My Policeman",
        fullTitle: "My Policeman (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BOTczM2JhOGMtMmQzOC00ZjgwLTlhNDEtMzU3NDRmMTQzMjM4XkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Michael Grandage (dir.), Harry Styles, Emma Corrin",
        imDbRating: "6.5",
        imDbRatingCount: "7878",
      },
      {
        id: "tt0094721",
        rank: "31",
        rankUpDown: "+7",
        title: "Beetlejuice",
        fullTitle: "Beetlejuice (1988)",
        year: "1988",
        image:
          "https://m.media-amazon.com/images/M/MV5BZDdmNjBlYTctNWU0MC00ODQxLWEzNDQtZGY1NmRhYjNmNDczXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Tim Burton (dir.), Alec Baldwin, Geena Davis",
        imDbRating: "7.5",
        imDbRatingCount: "306113",
      },
      {
        id: "tt10954984",
        rank: "32",
        rankUpDown: "-4",
        title: "Nope",
        fullTitle: "Nope (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BMGIyNTI3NWItNTJkOS00MGYyLWE4NjgtZDhjMWQ4Y2JkZTU5XkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Jordan Peele (dir.), Daniel Kaluuya, Keke Palmer",
        imDbRating: "6.9",
        imDbRatingCount: "153567",
      },
      {
        id: "tt11897478",
        rank: "33",
        rankUpDown: "-26",
        title: "The Stranger",
        fullTitle: "The Stranger (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BYzhmNWMyYjQtNTVlMC00MGUwLWFmYjEtM2NkNWY0ODQ2YmFiXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Thomas M. Wright (dir.), Joel Edgerton, Sean Harris",
        imDbRating: "6.6",
        imDbRatingCount: "10378",
      },
      {
        id: "tt9271672",
        rank: "34",
        rankUpDown: "-2",
        title: "Prey for the Devil",
        fullTitle: "Prey for the Devil (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BNzNjNmE4YTktMTZiNS00YTQ0LWExY2YtZTU2MGNiNzBiMzI5XkEyXkFqcGdeQXVyMTA0OTI1NDM2._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Daniel Stamm (dir.), Jacqueline Byers, Virginia Madsen",
        imDbRating: "5.2",
        imDbRatingCount: "3491",
      },
      {
        id: "tt7846844",
        rank: "35",
        rankUpDown: "+178",
        title: "Enola Holmes",
        fullTitle: "Enola Holmes (2020)",
        year: "2020",
        image:
          "https://m.media-amazon.com/images/M/MV5BZjNkNzk0ZjEtM2M1ZC00MmMxLTlmOWEtNWRlZTc1ZTUyNzY4XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Harry Bradbeer (dir.), Millie Bobby Brown, Henry Cavill",
        imDbRating: "6.6",
        imDbRatingCount: "180973",
      },
      {
        id: "tt10304142",
        rank: "36",
        rankUpDown: "-10",
        title: "Amsterdam",
        fullTitle: "Amsterdam (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BNDQwNzE0ZTItYmZjMC00NjI3LWFlNzctNTExZDY2NWE0Zjc0XkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "David O. Russell (dir.), Christian Bale, Margot Robbie",
        imDbRating: "6.1",
        imDbRatingCount: "17931",
      },
      {
        id: "tt0107688",
        rank: "37",
        rankUpDown: "+14",
        title: "The Nightmare Before Christmas",
        fullTitle: "The Nightmare Before Christmas (1993)",
        year: "1993",
        image:
          "https://m.media-amazon.com/images/M/MV5BNWE4OTNiM2ItMjY4Ni00ZTViLWFiZmEtZGEyNGY2ZmNlMzIyXkEyXkFqcGdeQXVyMDU5NDcxNw@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Henry Selick (dir.), Danny Elfman, Chris Sarandon",
        imDbRating: "7.9",
        imDbRatingCount: "338738",
      },
      {
        id: "tt14444726",
        rank: "38",
        rankUpDown: "-11",
        title: "Tár",
        fullTitle: "Tár (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BM2I0ZDcyYzItMGEyNi00YWVhLTlmNTQtOWVlYjE1ZGVhNWM0XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Todd Field (dir.), Cate Blanchett, Noémie Merlant",
        imDbRating: "8.2",
        imDbRatingCount: "3988",
      },
      {
        id: "tt6710474",
        rank: "39",
        rankUpDown: "-9",
        title: "Everything Everywhere All at Once",
        fullTitle: "Everything Everywhere All at Once (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BYTdiOTIyZTQtNmQ1OS00NjZlLWIyMTgtYzk5Y2M3ZDVmMDk1XkEyXkFqcGdeQXVyMTAzMDg4NzU0._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Dan Kwan (dir.), Michelle Yeoh, Stephanie Hsu",
        imDbRating: "8.1",
        imDbRatingCount: "234837",
      },
      {
        id: "tt0887261",
        rank: "40",
        rankUpDown: "-15",
        title: "Hellraiser",
        fullTitle: "Hellraiser (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BYWM1YTgxNjMtNzY2NC00YjVmLWE1ODUtNTdiYTI4YjZhODMwXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "David Bruckner (dir.), Odessa A’zion, Jamie Clayton",
        imDbRating: "6.0",
        imDbRatingCount: "31102",
      },
      {
        id: "tt4595186",
        rank: "41",
        rankUpDown: "-20",
        title: "Luckiest Girl Alive",
        fullTitle: "Luckiest Girl Alive (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BNzJlMTE3ODEtODRjOS00Zjg4LWE0ZTYtODAwMWMwNjFmZmQyXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Mike Barker (dir.), Mila Kunis, Chiara Aurelia",
        imDbRating: "6.4",
        imDbRatingCount: "37287",
      },
      {
        id: "tt15327088",
        rank: "42",
        rankUpDown: "-31",
        title: "Kantara",
        fullTitle: "Kantara (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BNjQyNGI5OWEtZjI1Yy00NDVjLWE4MTAtMzRlNzU1NzM2OGVkXkEyXkFqcGdeQXVyMTA1NzEzOTU1._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Rishab Shetty (dir.), Rishab Shetty, Sapthami Gowda",
        imDbRating: "9.1",
        imDbRatingCount: "65362",
      },
      {
        id: "tt8772262",
        rank: "43",
        rankUpDown: "+10",
        title: "Midsommar",
        fullTitle: "Midsommar (2019)",
        year: "2019",
        image:
          "https://m.media-amazon.com/images/M/MV5BMzQxNzQzOTQwM15BMl5BanBnXkFtZTgwMDQ2NTcwODM@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Ari Aster (dir.), Florence Pugh, Jack Reynor",
        imDbRating: "7.1",
        imDbRatingCount: "318639",
      },
      {
        id: "tt7144666",
        rank: "44",
        rankUpDown: "-1",
        title: "The Black Phone",
        fullTitle: "The Black Phone (2021)",
        year: "2021",
        image:
          "https://m.media-amazon.com/images/M/MV5BMWQxOGJlNTUtYTc1YS00NDkyLWExZjItMTFiYWEzMjAzYTdjXkEyXkFqcGdeQXVyNjk1Njg5NTA@._V1_UY176_CR6,0,128,176_AL_.jpg",
        crew: "Scott Derrickson (dir.), Mason Thames, Madeleine McGraw",
        imDbRating: "6.9",
        imDbRatingCount: "130972",
      },
      {
        id: "tt10343028",
        rank: "45",
        rankUpDown: "+30",
        title: "Armageddon Time",
        fullTitle: "Armageddon Time (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BMTNjMTI2YTMtMmM5Yi00MWUyLWI0NWMtN2EyY2FmZjIwMTVmXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "James Gray (dir.), Anne Hathaway, Jeremy Strong",
        imDbRating: "7.0",
        imDbRatingCount: "1765",
      },
      {
        id: "tt10192406",
        rank: "46",
        rankUpDown: "+762",
        title: "Causeway",
        fullTitle: "Causeway (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BMmYwOThkNzItYjNmNS00N2I1LTgzNjgtMTA5NGIzNDc1ZWI1XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Lila Neugebauer (dir.), Jennifer Lawrence, Brian Tyree Henry",
        imDbRating: "6.6",
        imDbRatingCount: "4562",
      },
      {
        id: "tt9764362",
        rank: "47",
        rankUpDown: "-6",
        title: "The Menu",
        fullTitle: "The Menu (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BMzdjNjI5MmYtODhiNS00NTcyLWEzZmUtYzVmODM5YzExNDE3XkEyXkFqcGdeQXVyMTAyMjQ3NzQ1._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Mark Mylod (dir.), Anya Taylor-Joy, Ralph Fiennes",
        imDbRating: "7.5",
        imDbRatingCount: "924",
      },
      {
        id: "tt15325794",
        rank: "48",
        rankUpDown: "-17",
        title: "Fall",
        fullTitle: "Fall (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BNGI3MWYwYjItNzZhYi00ZWIzLTkyMzYtN2JmNjg3ODg1NTg4XkEyXkFqcGdeQXVyMTMwMDA5ODU3._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Scott Mann (dir.), Grace Caroline Currey, Virginia Gardner",
        imDbRating: "6.4",
        imDbRatingCount: "40709",
      },
      {
        id: "tt10648342",
        rank: "49",
        rankUpDown: "-12",
        title: "Thor: Love and Thunder",
        fullTitle: "Thor: Love and Thunder (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BYmMxZWRiMTgtZjM0Ny00NDQxLWIxYWQtZDdlNDNkOTEzYTdlXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Taika Waititi (dir.), Chris Hemsworth, Natalie Portman",
        imDbRating: "6.3",
        imDbRatingCount: "305448",
      },
      {
        id: "tt1877830",
        rank: "50",
        rankUpDown: "-5",
        title: "The Batman",
        fullTitle: "The Batman (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BMDdmMTBiNTYtMDIzNi00NGVlLWIzMDYtZTk3MTQ3NGQxZGEwXkEyXkFqcGdeQXVyMzMwOTU5MDk@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Matt Reeves (dir.), Robert Pattinson, Zoë Kravitz",
        imDbRating: "7.9",
        imDbRatingCount: "619701",
      },
      {
        id: "tt11138512",
        rank: "51",
        rankUpDown: "-18",
        title: "The Northman",
        fullTitle: "The Northman (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BMzVlMmY2NTctODgwOC00NDMzLWEzMWYtM2RiYmIyNTNhMTI0XkEyXkFqcGdeQXVyNTAzNzgwNTg@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Robert Eggers (dir.), Alexander Skarsgård, Nicole Kidman",
        imDbRating: "7.1",
        imDbRatingCount: "188082",
      },
      {
        id: "tt18082758",
        rank: "52",
        rankUpDown: "9,015",
        title: "The Takeover",
        fullTitle: "The Takeover (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BZDE4ZTExZmMtYzA4NS00YzQwLTllMzgtNjQ0MDBjYTc3MzQxXkEyXkFqcGdeQXVyMTM0NTc2NDgw._V1_UX128_CR0,1,128,176_AL_.jpg",
        crew: "Annemarie van de Mond (dir.), Holly Mae Brood, Geza Weisz",
        imDbRating: "5.2",
        imDbRatingCount: "2257",
      },
      {
        id: "tt9574524",
        rank: "53",
        rankUpDown: "1,892",
        title: "Hebrews to Negroes: Wake Up Black America",
        fullTitle: "Hebrews to Negroes: Wake Up Black America (2018)",
        year: "2018",
        image:
          "https://m.media-amazon.com/images/M/MV5BNDBlNDFjNzgtNDNiZi00NmRmLWE0ZjctMGM5OTFmZTA0NGRhXkEyXkFqcGdeQXVyOTc1NjI1MjY@._V1_UY176_CR92,0,128,176_AL_.jpg",
        crew: "Ronald Dalton Jr. (dir.)",
        imDbRating: "3.0",
        imDbRatingCount: "541",
      },
      {
        id: "tt0020629",
        rank: "54",
        rankUpDown: "+254",
        title: "All Quiet on the Western Front",
        fullTitle: "All Quiet on the Western Front (1930)",
        year: "1930",
        image:
          "https://m.media-amazon.com/images/M/MV5BMDdlMzRjM2MtNjcxNy00MjgyLTkyZmYtY2ExODM0OTBkMzI0XkEyXkFqcGdeQXVyMzg1ODEwNQ@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Lewis Milestone (dir.), Lew Ayres, Louis Wolheim",
        imDbRating: "8.1",
        imDbRatingCount: "62692",
      },
      {
        id: "tt1396484",
        rank: "55",
        rankUpDown: "+11",
        title: "It",
        fullTitle: "It (2017)",
        year: "2017",
        image:
          "https://m.media-amazon.com/images/M/MV5BZDVkZmI0YzAtNzdjYi00ZjhhLWE1ODEtMWMzMWMzNDA0NmQ4XkEyXkFqcGdeQXVyNzYzODM3Mzg@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Andy Muschietti (dir.), Bill Skarsgård, Jaeden Martell",
        imDbRating: "7.3",
        imDbRatingCount: "545883",
      },
      {
        id: "tt22437050",
        rank: "56",
        rankUpDown: "+718",
        title: "Wild Is the Wind",
        fullTitle: "Wild Is the Wind (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BODRiYzI4ZWItNDRmOS00MWVmLWFmZGQtZGJlMjY4YjE3NGIzXkEyXkFqcGdeQXVyODAzMTg2NzU@._V1_UX128_CR0,1,128,176_AL_.jpg",
        crew: "Fabian Medea (dir.), Mothusi Magano, Frank Rautenbach",
        imDbRating: "5.5",
        imDbRatingCount: "814",
      },
      {
        id: "tt0499549",
        rank: "57",
        rankUpDown: "+84",
        title: "Avatar",
        fullTitle: "Avatar (2009)",
        year: "2009",
        image:
          "https://m.media-amazon.com/images/M/MV5BNjA3NGExZDktNDlhZC00NjYyLTgwNmUtZWUzMDYwMTZjZWUyXkEyXkFqcGdeQXVyMTU1MDM3NDk0._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "James Cameron (dir.), Sam Worthington, Zoe Saldana",
        imDbRating: "7.8",
        imDbRatingCount: "1243993",
      },
      {
        id: "tt9411972",
        rank: "58",
        rankUpDown: "-12",
        title: "Where the Crawdads Sing",
        fullTitle: "Where the Crawdads Sing (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BMTJmNGJmYTgtYjAxNy00YmMzLTk2YTYtMGIzMmUwNDMyMTY1XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UY176_CR6,0,128,176_AL_.jpg",
        crew: "Olivia Newman (dir.), Daisy Edgar-Jones, Taylor John Smith",
        imDbRating: "7.1",
        imDbRatingCount: "49277",
      },
      {
        id: "tt8656686",
        rank: "59",
        rankUpDown: "+152",
        title: "Run Sweetheart Run",
        fullTitle: "Run Sweetheart Run (2020)",
        year: "2020",
        image:
          "https://m.media-amazon.com/images/M/MV5BMGVkZDlkMDQtZThhMi00MzUxLThiZGMtYjQxOWVhZmZhNDcyXkEyXkFqcGdeQXVyMjY5ODI4NDk@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Shana Feste (dir.), Ella Balinska, Pilou Asbæk",
        imDbRating: "5.4",
        imDbRatingCount: "2683",
      },
      {
        id: "tt0085334",
        rank: "60",
        rankUpDown: "+428",
        title: "A Christmas Story",
        fullTitle: "A Christmas Story (1983)",
        year: "1983",
        image:
          "https://m.media-amazon.com/images/M/MV5BOWMyNjE0MzEtMzVjNy00NjIxLTg0ZjMtMWJhNGI1YmVjYTczL2ltYWdlXkEyXkFqcGdeQXVyNzc5MjA3OA@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Bob Clark (dir.), Peter Billingsley, Melinda Dillon",
        imDbRating: "7.9",
        imDbRatingCount: "148640",
      },
      {
        id: "tt0117571",
        rank: "61",
        rankUpDown: "+11",
        title: "Scream",
        fullTitle: "Scream (1996)",
        year: "1996",
        image:
          "https://m.media-amazon.com/images/M/MV5BMjA2NjU5MTg5OF5BMl5BanBnXkFtZTgwOTkyMzQxMDE@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Wes Craven (dir.), Neve Campbell, Courteney Cox",
        imDbRating: "7.4",
        imDbRatingCount: "343788",
      },
      {
        id: "tt8115900",
        rank: "62",
        rankUpDown: "+313",
        title: "The Bad Guys",
        fullTitle: "The Bad Guys (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BMDhkYmU0MzctMWEzNy00ODg1LWI3ZjAtMGZlZjkzNWVmMzVjXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Pierre Perifel (dir.), Sam Rockwell, Marc Maron",
        imDbRating: "6.8",
        imDbRatingCount: "37088",
      },
      {
        id: "tt0092099",
        rank: "63",
        rankUpDown: "-14",
        title: "Top Gun",
        fullTitle: "Top Gun (1986)",
        year: "1986",
        image:
          "https://m.media-amazon.com/images/M/MV5BZjQxYTA3ODItNzgxMy00N2Y2LWJlZGMtMTRlM2JkZjI1ZDhhXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Tony Scott (dir.), Tom Cruise, Tim Robbins",
        imDbRating: "6.9",
        imDbRatingCount: "435750",
      },
      {
        id: "tt0081505",
        rank: "64",
        rankUpDown: "+28",
        title: "The Shining",
        fullTitle: "The Shining (1980)",
        year: "1980",
        image:
          "https://m.media-amazon.com/images/M/MV5BZWFlYmY2MGEtZjVkYS00YzU4LTg0YjQtYzY1ZGE3NTA5NGQxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Stanley Kubrick (dir.), Jack Nicholson, Shelley Duvall",
        imDbRating: "8.4",
        imDbRatingCount: "1016241",
      },
      {
        id: "tt0073629",
        rank: "65",
        rankUpDown: "+6",
        title: "The Rocky Horror Picture Show",
        fullTitle: "The Rocky Horror Picture Show (1975)",
        year: "1975",
        image:
          "https://m.media-amazon.com/images/M/MV5BOGIzYjM3YzMtMjk5ZS00NDY2LTllMjEtNjYwZjhmMDNhMDBkXkEyXkFqcGdeQXVyODUzMjQxMTA@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Jim Sharman (dir.), Tim Curry, Susan Sarandon",
        imDbRating: "7.4",
        imDbRatingCount: "153680",
      },
      {
        id: "tt11245972",
        rank: "66",
        rankUpDown: "+3",
        title: "Scream",
        fullTitle: "Scream (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BYjExYTcwYmYtMWY2Zi00MGJlLTk3YjUtZTU1Zjg4MDc0Y2FjXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Matt Bettinelli-Olpin (dir.), Neve Campbell, Courteney Cox",
        imDbRating: "6.3",
        imDbRatingCount: "110513",
      },
      {
        id: "tt1655389",
        rank: "67",
        rankUpDown: "-31",
        title: "Blonde",
        fullTitle: "Blonde (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BNDk2YTA1MGYtMGNjMi00YTJlLWI1YjItMjBjOGJlZGIwZmYzXkEyXkFqcGdeQXVyODA0MjgyNzM@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Andrew Dominik (dir.), Ana de Armas, Lily Fisher",
        imDbRating: "5.5",
        imDbRatingCount: "48252",
      },
      {
        id: "tt10999120",
        rank: "68",
        rankUpDown: "+250",
        title: "Spirited",
        fullTitle: "Spirited (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BY2RlZGFmYjAtNGZiMi00YjQ5LWE0ZmQtZmIyM2VmMjRhMTJlXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Sean Anders (dir.), Will Ferrell, Ryan Reynolds",
        imDbRating: "7.2",
        imDbRatingCount: "127",
      },
      {
        id: "tt20782072",
        rank: "69",
        rankUpDown: "+904",
        title: "Feed",
        fullTitle: "Feed (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BYjk1NTcwZTgtMDUxNS00ZGJlLTk2MmQtYWJhZmY5MDNhN2Q5XkEyXkFqcGdeQXVyMTE5NzkyNTM@._V1_UX128_CR0,1,128,176_AL_.jpg",
        crew: "Johannes Persson (dir.), Vincent Grahl, Sofia Kappel",
        imDbRating: "6.8",
        imDbRatingCount: "5993",
      },
      {
        id: "tt10954600",
        rank: "70",
        rankUpDown: "-65",
        title: "Ant-Man and the Wasp: Quantumania",
        fullTitle: "Ant-Man and the Wasp: Quantumania (2023)",
        year: "2023",
        image:
          "https://m.media-amazon.com/images/M/MV5BNDgyNGM4NTYtN2M3MS00YTY2LTk0OWUtZmIzYjg3MmQ0OGM4XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Peyton Reed (dir.), Paul Rudd, Evangeline Lilly",
        imDbRating: "",
        imDbRatingCount: "0",
      },
      {
        id: "tt12683756",
        rank: "71",
        rankUpDown: "-10",
        title: "The Chalk Line",
        fullTitle: "The Chalk Line (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BYjU0ZjJiYzEtMGE4Mi00ZGM3LTlhZTgtNzM0MzM2ZTkyMGJkXkEyXkFqcGdeQXVyMjc4MjcxNzI@._V1_UX128_CR0,1,128,176_AL_.jpg",
        crew: "Ignacio Tatay (dir.), Elena Anaya, Pablo Molinero",
        imDbRating: "6.0",
        imDbRatingCount: "3445",
      },
      {
        id: "tt0144084",
        rank: "72",
        rankUpDown: "-16",
        title: "American Psycho",
        fullTitle: "American Psycho (2000)",
        year: "2000",
        image:
          "https://m.media-amazon.com/images/M/MV5BZTM2ZGJmNjQtN2UyOS00NjcxLWFjMDktMDE2NzMyNTZlZTBiXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Mary Harron (dir.), Christian Bale, Justin Theroux",
        imDbRating: "7.6",
        imDbRatingCount: "611571",
      },
      {
        id: "tt19724142",
        rank: "73",
        rankUpDown: "+29",
        title: "Hellhole",
        fullTitle: "Hellhole (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BOWI3ZmU3NjUtM2JjYS00YmYzLThkNzctNGVhZGRiYzRkYmQ1XkEyXkFqcGdeQXVyODAzMTg2NzU@._V1_UX128_CR0,1,128,176_AL_.jpg",
        crew: "Bartosz M. Kowalski (dir.), Piotr Zurawski, Olaf Lubaszenko",
        imDbRating: "5.7",
        imDbRatingCount: "2893",
      },
      {
        id: "tt13320622",
        rank: "74",
        rankUpDown: "+2",
        title: "The Lost City",
        fullTitle: "The Lost City (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BMmIwYzFhODAtY2I1YS00ZDdmLTkyYWQtZjI5NDIwMDc2MjEyXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Aaron Nee (dir.), Sandra Bullock, Channing Tatum",
        imDbRating: "6.1",
        imDbRatingCount: "113774",
      },
      {
        id: "tt0070047",
        rank: "75",
        rankUpDown: "+52",
        title: "The Exorcist",
        fullTitle: "The Exorcist (1973)",
        year: "1973",
        image:
          "https://m.media-amazon.com/images/M/MV5BYWFlZGY2NDktY2ZjOS00ZWNkLTg0ZDAtZDY4MTM1ODU4ZjljXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "William Friedkin (dir.), Ellen Burstyn, Max von Sydow",
        imDbRating: "8.1",
        imDbRatingCount: "407642",
      },
      {
        id: "tt1502407",
        rank: "76",
        rankUpDown: "-11",
        title: "Halloween",
        fullTitle: "Halloween (2018)",
        year: "2018",
        image:
          "https://m.media-amazon.com/images/M/MV5BMmMzNjJhYjUtNzFkZi00MWQ4LWJiMDEtYWM0NTAzNGZjMTI3XkEyXkFqcGdeQXVyOTE2OTMwNDk@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "David Gordon Green (dir.), Jamie Lee Curtis, Judy Greer",
        imDbRating: "6.5",
        imDbRatingCount: "155804",
      },
      {
        id: "tt0241527",
        rank: "77",
        rankUpDown: "-15",
        title: "Harry Potter and the Sorcerer's Stone",
        fullTitle: "Harry Potter and the Sorcerer's Stone (2001)",
        year: "2001",
        image:
          "https://m.media-amazon.com/images/M/MV5BMzkyZGFlOWQtZjFlMi00N2YwLWE2OWQtYTgxY2NkNmM1NjMwXkEyXkFqcGdeQXVyNjY1NTM1MzA@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Chris Columbus (dir.), Daniel Radcliffe, Rupert Grint",
        imDbRating: "7.6",
        imDbRatingCount: "775143",
      },
      {
        id: "tt9731598",
        rank: "78",
        rankUpDown: "-38",
        title: "Bros",
        fullTitle: "Bros (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BMzI4MDg3NDEtOTg1OC00MDdjLWEzY2QtMmFmMWNlNTcxZDIxXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_UY176_CR6,0,128,176_AL_.jpg",
        crew: "Nicholas Stoller (dir.), Billy Eichner, Luke Macfarlane",
        imDbRating: "6.4",
        imDbRatingCount: "19062",
      },
      {
        id: "tt0101272",
        rank: "79",
        rankUpDown: "+45",
        title: "The Addams Family",
        fullTitle: "The Addams Family (1991)",
        year: "1991",
        image:
          "https://m.media-amazon.com/images/M/MV5BMmJhZTlhNzUtNzAwZC00YjQ2LTkxOGEtNzBmOWVkMmUxNTBiXkEyXkFqcGdeQXVyMTExNDQ2MTI@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Barry Sonnenfeld (dir.), Anjelica Huston, Raul Julia",
        imDbRating: "6.9",
        imDbRatingCount: "157902",
      },
      {
        id: "tt7784604",
        rank: "80",
        rankUpDown: "+23",
        title: "Hereditary",
        fullTitle: "Hereditary (2018)",
        year: "2018",
        image:
          "https://m.media-amazon.com/images/M/MV5BOTU5MDg3OGItZWQ1Ny00ZGVmLTg2YTUtMzBkYzQ1YWIwZjlhXkEyXkFqcGdeQXVyNTAzMTY4MDA@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Ari Aster (dir.), Toni Collette, Milly Shapiro",
        imDbRating: "7.3",
        imDbRatingCount: "314252",
      },
      {
        id: "tt3704428",
        rank: "81",
        rankUpDown: "-31",
        title: "Elvis",
        fullTitle: "Elvis (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BYzMzNTJjYmMtZTkxNS00MjI4LWI3YmQtOTQ4MDZjZDJlZjQyXkEyXkFqcGdeQXVyNjc0NzQzNTM@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Baz Luhrmann (dir.), Tom Hanks, Austin Butler",
        imDbRating: "7.4",
        imDbRatingCount: "143510",
      },
      {
        id: "tt0111161",
        rank: "82",
        rankUpDown: "-12",
        title: "The Shawshank Redemption",
        fullTitle: "The Shawshank Redemption (1994)",
        year: "1994",
        image:
          "https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Frank Darabont (dir.), Tim Robbins, Morgan Freeman",
        imDbRating: "9.3",
        imDbRatingCount: "2660364",
      },
      {
        id: "tt14208870",
        rank: "83",
        rankUpDown: "+132",
        title: "The Fabelmans",
        fullTitle: "The Fabelmans (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BZGM1MzczNmQtMjBmYS00NTRhLWI0MzctNTFkZDc4OGUyODdjXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Steven Spielberg (dir.), Michelle Williams, Gabriel LaBelle",
        imDbRating: "8.3",
        imDbRatingCount: "964",
      },
      {
        id: "tt0862856",
        rank: "84",
        rankUpDown: "+13",
        title: "Trick 'r Treat",
        fullTitle: "Trick 'r Treat (2007)",
        year: "2007",
        image:
          "https://m.media-amazon.com/images/M/MV5BYmIyY2E5YjMtZDA3NC00MmIzLWFkZmItNzVlODllZWNlZmRkXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Michael Dougherty (dir.), Anna Paquin, Brian Cox",
        imDbRating: "6.7",
        imDbRatingCount: "95097",
      },
      {
        id: "tt11564570",
        rank: "85",
        rankUpDown: "-31",
        title: "Glass Onion: A Knives Out Mystery",
        fullTitle: "Glass Onion: A Knives Out Mystery (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BYmZlZDZkZjYtNzE5Mi00ODFhLTk2OTgtZWVmODBiZTI4NGFiXkEyXkFqcGdeQXVyMTE5MTg5NDIw._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Rian Johnson (dir.), Daniel Craig, Edward Norton",
        imDbRating: "8.1",
        imDbRatingCount: "1360",
      },
      {
        id: "tt10168670",
        rank: "86",
        rankUpDown: "+84",
        title: "Bones and All",
        fullTitle: "Bones and All (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BMDY0ZjUyYTItZmFlYS00MjI5LTljNmItODliMDkwMmY4ZTVkXkEyXkFqcGdeQXVyMTU0ODA5OTE2._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Luca Guadagnino (dir.), Timothée Chalamet, Taylor Russell",
        imDbRating: "7.1",
        imDbRatingCount: "1115",
      },
      {
        id: "tt16183464",
        rank: "87",
        rankUpDown: "1,111",
        title: "One Piece Film: Red",
        fullTitle: "One Piece Film: Red (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BODY4OWM5M2UtM2Y1Yi00YjAyLTlhMDktMDkzZjFmMjI5MmI5XkEyXkFqcGdeQXVyMTA1NjQyNjkw._V1_UX128_CR0,1,128,176_AL_.jpg",
        crew: "Gorô Taniguchi (dir.), Mayumi Tanaka, Kazuya Nakai",
        imDbRating: "6.9",
        imDbRatingCount: "6047",
      },
      {
        id: "tt4263482",
        rank: "88",
        rankUpDown: "-8",
        title: "The Witch",
        fullTitle: "The Witch (2015)",
        year: "2015",
        image:
          "https://m.media-amazon.com/images/M/MV5BMTUyNzkwMzAxOF5BMl5BanBnXkFtZTgwMzc1OTk1NjE@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Robert Eggers (dir.), Anya Taylor-Joy, Ralph Ineson",
        imDbRating: "6.9",
        imDbRatingCount: "262283",
      },
      {
        id: "tt12004038",
        rank: "89",
        rankUpDown: "-37",
        title: "Watcher",
        fullTitle: "Watcher (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BMTNkNjU4OGYtODM3NS00NzM1LWFkZWItZTExNzdjYTAwMmRlXkEyXkFqcGdeQXVyMTE1MzI2NzIz._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Chloe Okuno (dir.), Maika Monroe, Karl Glusman",
        imDbRating: "6.3",
        imDbRatingCount: "22588",
      },
      {
        id: "tt0087800",
        rank: "90",
        rankUpDown: "-12",
        title: "A Nightmare on Elm Street",
        fullTitle: "A Nightmare on Elm Street (1984)",
        year: "1984",
        image:
          "https://m.media-amazon.com/images/M/MV5BNzFjZmM1ODgtMDBkMS00NWFlLTg2YmUtZjc3ZTgxMjE1OTI2L2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Wes Craven (dir.), Heather Langenkamp, Johnny Depp",
        imDbRating: "7.4",
        imDbRatingCount: "241346",
      },
      {
        id: "tt8110652",
        rank: "91",
        rankUpDown: "-24",
        title: "Bodies Bodies Bodies",
        fullTitle: "Bodies Bodies Bodies (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BYTA2ODg5ZjgtOTU2My00MzFkLWI0NzMtZmQ5MmRhMWU1NzhlXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Halina Reijn (dir.), Amandla Stenberg, Maria Bakalova",
        imDbRating: "6.3",
        imDbRatingCount: "27725",
      },
      {
        id: "tt15289240",
        rank: "92",
        rankUpDown: "-57",
        title: "The Curse of Bridge Hollow",
        fullTitle: "The Curse of Bridge Hollow (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BMjUzMzMxODYtNjc1OS00NDNiLWIzMzMtNTBhMjE5NDllNzY0XkEyXkFqcGdeQXVyMzE5ODc1OA@@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Jeff Wadlow (dir.), Marlon Wayans, Priah Ferguson",
        imDbRating: "5.6",
        imDbRatingCount: "8048",
      },
      {
        id: "tt0087332",
        rank: "93",
        rankUpDown: "+14",
        title: "Ghostbusters",
        fullTitle: "Ghostbusters (1984)",
        year: "1984",
        image:
          "https://m.media-amazon.com/images/M/MV5BMTkxMjYyNzgwMl5BMl5BanBnXkFtZTgwMTE3MjYyMTE@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Ivan Reitman (dir.), Bill Murray, Dan Aykroyd",
        imDbRating: "7.8",
        imDbRatingCount: "415477",
      },
      {
        id: "tt10665338",
        rank: "94",
        rankUpDown: "-20",
        title: "Halloween Kills",
        fullTitle: "Halloween Kills (2021)",
        year: "2021",
        image:
          "https://m.media-amazon.com/images/M/MV5BM2RmMGY2Y2UtNjA1NS00NGE4LThiNzItMmE1NTk5NzI5NmE0XkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "David Gordon Green (dir.), Jamie Lee Curtis, Judy Greer",
        imDbRating: "5.5",
        imDbRatingCount: "86117",
      },
      {
        id: "tt0084516",
        rank: "95",
        rankUpDown: "+13",
        title: "Poltergeist",
        fullTitle: "Poltergeist (1982)",
        year: "1982",
        image:
          "https://m.media-amazon.com/images/M/MV5BODJiZTU1ZTMtZTEzMy00NzFmLWJjNzctZTc2MDcwZjE1MDBjXkEyXkFqcGdeQXVyMTUzMDUzNTI3._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Tobe Hooper (dir.), JoBeth Williams, Heather O'Rourke",
        imDbRating: "7.3",
        imDbRatingCount: "165751",
      },
      {
        id: "tt4960748",
        rank: "96",
        rankUpDown: "-13",
        title: "Till",
        fullTitle: "Till (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BOTU5NzgxODMtMjg2Mi00YTAxLTg4MTMtNDJmNWU5MTU5ODJjXkEyXkFqcGdeQXVyMTMzNDE5NDM2._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Chinonye Chukwu (dir.), Danielle Deadwyler, Jalyn Hall",
        imDbRating: "7.6",
        imDbRatingCount: "1684",
      },
      {
        id: "tt0068646",
        rank: "97",
        rankUpDown: "-20",
        title: "The Godfather",
        fullTitle: "The Godfather (1972)",
        year: "1972",
        image:
          "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX128_CR0,1,128,176_AL_.jpg",
        crew: "Francis Ford Coppola (dir.), Marlon Brando, Al Pacino",
        imDbRating: "9.2",
        imDbRatingCount: "1843701",
      },
      {
        id: "tt5108870",
        rank: "98",
        rankUpDown: "+79",
        title: "Morbius",
        fullTitle: "Morbius (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BNTA3N2Q0ZTAtODJjNy00MmQzLWJlMmItOGFmNDI0ODgxN2QwXkEyXkFqcGdeQXVyMTM0NTUzNDIy._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Daniel Espinosa (dir.), Jared Leto, Matt Smith",
        imDbRating: "5.2",
        imDbRatingCount: "118194",
      },
      {
        id: "tt0120737",
        rank: "99",
        rankUpDown: "-44",
        title: "The Lord of the Rings: The Fellowship of the Ring",
        fullTitle: "The Lord of the Rings: The Fellowship of the Ring (2001)",
        year: "2001",
        image:
          "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Peter Jackson (dir.), Elijah Wood, Ian McKellen",
        imDbRating: "8.8",
        imDbRatingCount: "1863280",
      },
      {
        id: "tt11866324",
        rank: "100",
        rankUpDown: "-12",
        title: "Prey",
        fullTitle: "Prey (2022)",
        year: "2022",
        image:
          "https://m.media-amazon.com/images/M/MV5BMDBlMDYxMDktOTUxMS00MjcxLWE2YjQtNjNhMjNmN2Y3ZDA1XkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_UX128_CR0,3,128,176_AL_.jpg",
        crew: "Dan Trachtenberg (dir.), Amber Midthunder, Dakota Beavers",
        imDbRating: "7.2",
        imDbRatingCount: "182013",
      },
    ],
    errorMessage: "",
  }
  );
    // useEffect(() => {
    //   async function fetchData() {
    //     const res = await fetch(
    //       `https://imdb-api.com/en/API/MostPopularMovies/${process.env.NEXT_PUBLIC_RAPID_API_HOST}`
    //     );
    //     const data = await res.json();
    //     console.log(data);
    //     //const results = data.items;
    //     setdata(data);
    //   }
    //   fetchData();
    // }, []);

  const handleRemove = (element) => {
    console.log(element.id)
    const Removeddata = data?.items?.filter((e) => e.id !== element.id)
    setdata((prev) => ({  
      ...prev,
      items: Removeddata
    }))
   
  }




  return (
    <>
      <h2 className={styles.recc}>Recommended movies</h2>
      <div className={styles.container}>
        {data?.items?.map((element, index) => {
          return (
           <Reco element={element} key = {index} index={index} handleRemove={handleRemove}/>
          );
        })}
      </div>
      <div className={styles.container}>
        {data?.items?.map((element, index) => {
          return (
           <Reco2 element={element} key = {index} index={index} handleRemove={handleRemove}/>
          );
        })}
      </div>
    </>
  );
}

export default Elements;
